chore(deps): prebuild for electron 13
bump nan to fix build error in nan.h due to deprecation

In file included from ../../nan/nan.h:2884:
../../nan/nan_typedarray_contents.h:34:43: error: no member named 'GetContents' in 'v8::ArrayBuffer'
      data   = static_cast<char*>(buffer->GetContents().Data()) + byte_offset;
                                  ~~~~~~  ^
1 error generated.

Signed-off-by: Christoph Settgast <csett86@web.de>